# --- Empty Makefile ---
all: ;

TAR_FILES=README Makefile VMtranslator VMtranslator.py CodeWriter.py Command.py Parser.py
TAR_FLAGS=-cvf
TAR_NAME=project7.tar
TAR=tar

tar: 
	$(TAR) $(TAR_FLAGS) $(TAR_NAME) $(TAR_FILES)

.PHONY: all tar
